# Generated by Django 4.1.6 on 2023-02-06 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("address", models.CharField(max_length=256)),
                ("phone", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("no", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32)),
                ("type", models.CharField(max_length=32)),
                ("balance", models.FloatField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
            ],
        ),
    ]
