# Generated by Django 4.1.6 on 2023-02-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customerid", models.AutoField(primary_key=True, serialize=False)),
                ("accountno", models.CharField(max_length=256)),
                ("firstname", models.CharField(max_length=32)),
                ("lastname", models.CharField(max_length=32)),
                ("address", models.CharField(max_length=512)),
                ("phone", models.CharField(max_length=16)),
            ],
        ),
    ]
