# Generated by Django 4.1.6 on 2023-02-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="name",
        ),
        migrations.AlterField(
            model_name="account",
            name="no",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(default="checking", max_length=32),
        ),
    ]
